name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
          cache: gradle
      - run:
          ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: build/reports
